#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE}")/bash-boilerplate.sh"

echo "Running dummy-concourse-repo build..."
echo "Ref (branch): $(git rev-parse --abbrev-ref HEAD)"
echo "SHA: $(git rev-parse HEAD)"
